Memtext\Model\ShortDict:
  type: entity
  table: shortdict
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    keyword:
      type: string
    definition:
      type: text
