Memtext\Model\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    login:
      type: string
    email:
      type: string
    salt:
      type: string
    saltedHash:
      type: string
  oneToMany:
    texts:
      targetEntity: Text
      mappedBy: author
